// Temporary seed script — run once to populate test movements
import "dotenv/config";
import mongoose from "mongoose";
import { Movement } from "./models/Movement.js";

const MONGODB_URI = process.env.MONGODB_URI!;

const testMovements = [
    // --- Gymnastics (G) ---
    {
        name: "Air Squat",
        modality: "G",
        stimulusTags: ["endurance", "stamina"],
        equipmentRequired: [],
        bodyweightOnly: true,
        family: "squat",
        variants: ["Pistol Squat", "Jumping Squat"],
        progressions: [
            { level: "beginner", variant: "Box Squat" },
            { level: "scaled", variant: "Air Squat" },
            { level: "rx", variant: "Air Squat" },
        ],
        isLoaded: false,
        description: "Foundational bodyweight squat.",
        cues: ["Heels down", "Chest up", "Crease below knee"],
    },
    {
        name: "Pull-Up",
        modality: "G",
        stimulusTags: ["strength", "skill"],
        equipmentRequired: ["pullup_bar"],
        bodyweightOnly: false,
        family: "pull",
        variants: ["Strict Pull-Up", "Kipping Pull-Up", "Butterfly Pull-Up"],
        progressions: [
            { level: "beginner", variant: "Ring Row" },
            { level: "scaled", variant: "Banded Pull-Up" },
            { level: "rx", variant: "Pull-Up" },
        ],
        isLoaded: false,
        description: "Vertical pulling movement.",
        cues: ["Lats engaged", "Chin over bar", "Full extension"],
    },
    {
        name: "Push-Up",
        modality: "G",
        stimulusTags: ["strength", "endurance"],
        equipmentRequired: [],
        bodyweightOnly: true,
        family: "press",
        variants: ["Hand-Release Push-Up", "Diamond Push-Up"],
        progressions: [
            { level: "beginner", variant: "Elevated Push-Up" },
            { level: "scaled", variant: "Push-Up" },
            { level: "rx", variant: "Hand-Release Push-Up" },
        ],
        isLoaded: false,
        description: "Horizontal pressing.",
        cues: ["Core tight", "Chest to floor", "Elbows in"],
    },
    {
        name: "Burpee",
        modality: "G",
        stimulusTags: ["endurance", "stamina"],
        equipmentRequired: [],
        bodyweightOnly: true,
        family: "full_body",
        variants: ["Target Burpee", "Bar-Facing Burpee"],
        progressions: [
            { level: "beginner", variant: "Step-Back Burpee" },
            { level: "scaled", variant: "Burpee" },
            { level: "rx", variant: "Burpee" },
        ],
        isLoaded: false,
        description: "Metabolic conditioning.",
        cues: ["Chest to floor", "Jump and clap"],
    },
    {
        name: "Box Jump",
        abbreviation: "BJ",
        modality: "G",
        stimulusTags: ["power", "coordination"],
        equipmentRequired: ["box"],
        bodyweightOnly: false,
        family: "jump",
        variants: ["Box Step-Up", "Box Jump-Over"],
        progressions: [
            { level: "beginner", variant: "Box Step-Up" },
            { level: "scaled", variant: "Box Jump (20in)" },
            { level: "rx", variant: "Box Jump (24in)" },
        ],
        isLoaded: false,
        description: "Explosive jump.",
        cues: ["Land soft", "Stand tall"],
    },
    {
        name: "Sit-Up",
        modality: "G",
        stimulusTags: ["endurance"],
        equipmentRequired: [],
        bodyweightOnly: true,
        family: "core",
        variants: ["V-Up", "GHD Sit-Up"],
        progressions: [
            { level: "beginner", variant: "Sit-Up" },
            { level: "scaled", variant: "Sit-Up" },
            { level: "rx", variant: "Sit-Up" },
        ],
        isLoaded: false,
        description: "AbMat sit-up.",
        cues: ["Touch floor behind head", "Touch toes"],
    },
    {
        name: "Toes-to-Bar",
        abbreviation: "T2B",
        modality: "G",
        stimulusTags: ["skill", "stamina"],
        equipmentRequired: ["pullup_bar"],
        bodyweightOnly: false,
        family: "core",
        variants: ["Knees-to-Chest"],
        progressions: [
            { level: "beginner", variant: "Knee Raise" },
            { level: "scaled", variant: "Toes-to-Bar" },
            { level: "rx", variant: "Toes-to-Bar" },
        ],
        isLoaded: false,
        description: "Hanging abdominal work.",
        cues: ["Big kip", "Toes touch bar"],
    },
    {
        name: "Muscle-Up",
        abbreviation: "MU",
        modality: "G",
        stimulusTags: ["skill", "power", "strength"],
        equipmentRequired: ["rings"],
        bodyweightOnly: false,
        family: "pull",
        variants: ["Bar Muscle-Up"],
        progressions: [
            { level: "beginner", variant: "Ring Dip" },
            { level: "scaled", variant: "Chest-to-Bar Pull-Up" },
            { level: "rx", variant: "Muscle-Up" },
        ],
        isLoaded: false,
        description: "Advanced gymnastics.",
        cues: ["Fast turnover", "Lock out dip"],
    },
    {
        name: "Handstand Push-Up",
        abbreviation: "HSPU",
        modality: "G",
        stimulusTags: ["skill", "strength"],
        equipmentRequired: [],
        bodyweightOnly: true,
        family: "press",
        variants: ["Strict HSPU"],
        progressions: [
            { level: "beginner", variant: "Dumbbell Press" },
            { level: "scaled", variant: "Pike Push-Up" },
            { level: "rx", variant: "Handstand Push-Up" },
        ],
        isLoaded: false,
        description: "Inverted pressing.",
        cues: ["Head forward", "Big kick"],
    },
    {
        name: "Pistol Squat",
        modality: "G",
        stimulusTags: ["skill", "balance", "strength"],
        equipmentRequired: [],
        bodyweightOnly: true,
        family: "squat",
        variants: [],
        progressions: [
            { level: "beginner", variant: "Box Step-Up" },
            { level: "scaled", variant: "Assisted Pistol" },
            { level: "rx", variant: "Pistol Squat" },
        ],
        isLoaded: false,
        description: "Single-leg squat.",
        cues: ["Balance", "Heel down"],
    },
    {
        name: "Ring Dip",
        modality: "G",
        stimulusTags: ["strength", "stamina"],
        equipmentRequired: ["rings"],
        bodyweightOnly: false,
        family: "press",
        variants: [],
        progressions: [
            { level: "beginner", variant: "Bench Dip" },
            { level: "scaled", variant: "Banded Ring Dip" },
            { level: "rx", variant: "Ring Dip" },
        ],
        isLoaded: false,
        description: "Unstable pressing.",
        cues: ["Rings close", "Full lockout"],
    },

    // --- Weightlifting (W) ---
    {
        name: "Deadlift",
        abbreviation: "DL",
        modality: "W",
        stimulusTags: ["strength", "power"],
        equipmentRequired: ["barbell"],
        bodyweightOnly: false,
        family: "hinge",
        variants: ["Sumo Deadlift"],
        progressions: [
            { level: "beginner", variant: "KB Deadlift" },
            { level: "scaled", variant: "Deadlift" },
            { level: "rx", variant: "Deadlift" },
        ],
        defaultLoadKg: { beginner: 20, scaled: 40, rx: 100 },
        isLoaded: true,
        description: "Foundational hinge.",
        cues: ["Flat back", "Heels down"],
    },
    {
        name: "Back Squat",
        abbreviation: "BS",
        modality: "W",
        stimulusTags: ["strength"],
        equipmentRequired: ["barbell", "rack"],
        bodyweightOnly: false,
        family: "squat",
        variants: [],
        progressions: [
            { level: "beginner", variant: "Air Squat" },
            { level: "scaled", variant: "Back Squat" },
            { level: "rx", variant: "Back Squat" },
        ],
        defaultLoadKg: { beginner: 20, scaled: 40, rx: 80 },
        isLoaded: true,
        description: "Posterior chain strength.",
        cues: ["Big breath", "Drive up"],
    },
    {
        name: "Front Squat",
        abbreviation: "FS",
        modality: "W",
        stimulusTags: ["strength"],
        equipmentRequired: ["barbell", "rack"],
        bodyweightOnly: false,
        family: "squat",
        variants: [],
        progressions: [
            { level: "beginner", variant: "Goblet Squat" },
            { level: "scaled", variant: "Front Squat" },
            { level: "rx", variant: "Front Squat" },
        ],
        defaultLoadKg: { beginner: 15, scaled: 30, rx: 60 },
        isLoaded: true,
        description: "Anterior load strength.",
        cues: ["Elbows high"],
    },
    {
        name: "Overhead Squat",
        abbreviation: "OHS",
        modality: "W",
        stimulusTags: ["skill", "flexibility", "strength"],
        equipmentRequired: ["barbell"],
        bodyweightOnly: false,
        family: "squat",
        variants: [],
        progressions: [
            { level: "beginner", variant: "PVC OHS" },
            { level: "scaled", variant: "Overhead Squat" },
            { level: "rx", variant: "Overhead Squat" },
        ],
        defaultLoadKg: { beginner: 0, scaled: 20, rx: 43 },
        isLoaded: true,
        description: "Core and shoulder stability.",
        cues: ["Armpits forward"],
    },
    {
        name: "Shoulder Press",
        abbreviation: "SP",
        modality: "W",
        stimulusTags: ["strength"],
        equipmentRequired: ["barbell", "rack"],
        bodyweightOnly: false,
        family: "press",
        variants: [],
        progressions: [
            { level: "beginner", variant: "DB Press" },
            { level: "scaled", variant: "Shoulder Press" },
            { level: "rx", variant: "Shoulder Press" },
        ],
        defaultLoadKg: { beginner: 10, scaled: 20, rx: 40 },
        isLoaded: true,
        description: "Strict overhead pressing.",
        cues: ["Core locked"],
    },
    {
        name: "Push Press",
        abbreviation: "PP",
        modality: "W",
        stimulusTags: ["power", "strength"],
        equipmentRequired: ["barbell", "rack"],
        bodyweightOnly: false,
        family: "press",
        variants: [],
        progressions: [
            { level: "beginner", variant: "DB Push Press" },
            { level: "scaled", variant: "Push Press" },
            { level: "rx", variant: "Push Press" },
        ],
        defaultLoadKg: { beginner: 15, scaled: 30, rx: 50 },
        isLoaded: true,
        description: "Dip and drive pressing.",
        cues: ["Heels down on dip"],
    },
    {
        name: "Push Jerk",
        abbreviation: "PJ",
        modality: "W",
        stimulusTags: ["power", "skill"],
        equipmentRequired: ["barbell", "rack"],
        bodyweightOnly: false,
        family: "press",
        variants: ["Split Jerk"],
        progressions: [
            { level: "beginner", variant: "Push Press" },
            { level: "scaled", variant: "Push Jerk" },
            { level: "rx", variant: "Push Jerk" },
        ],
        defaultLoadKg: { beginner: 15, scaled: 40, rx: 60 },
        isLoaded: true,
        description: "Dynamic overhead movement.",
        cues: ["Fast drop"],
    },
    {
        name: "Clean",
        modality: "W",
        stimulusTags: ["power", "skill", "strength"],
        equipmentRequired: ["barbell"],
        bodyweightOnly: false,
        family: "pull",
        variants: ["Hang Power Clean", "Squat Clean"],
        progressions: [
            { level: "beginner", variant: "DB Clean" },
            { level: "scaled", variant: "Power Clean" },
            { level: "rx", variant: "Clean" },
        ],
        defaultLoadKg: { beginner: 20, scaled: 40, rx: 60 },
        isLoaded: true,
        description: "Olympic pulling.",
        cues: ["Jump and shrug"],
    },
    {
        name: "Snatch",
        modality: "W",
        stimulusTags: ["power", "skill", "flexibility"],
        equipmentRequired: ["barbell"],
        bodyweightOnly: false,
        family: "pull",
        variants: ["Power Snatch", "Squat Snatch"],
        progressions: [
            { level: "beginner", variant: "PVC Snatch" },
            { level: "scaled", variant: "Power Snatch" },
            { level: "rx", variant: "Snatch" },
        ],
        defaultLoadKg: { beginner: 10, scaled: 30, rx: 43 },
        isLoaded: true,
        description: "Dynamic full-body power.",
        cues: ["Fast elbows"],
    },
    {
        name: "Thruster",
        modality: "W",
        stimulusTags: ["power", "stamina"],
        equipmentRequired: ["barbell"],
        bodyweightOnly: false,
        family: "squat",
        variants: ["DB Thruster"],
        progressions: [
            { level: "beginner", variant: "Goblet Thruster" },
            { level: "scaled", variant: "Thruster" },
            { level: "rx", variant: "Thruster" },
        ],
        defaultLoadKg: { beginner: 10, scaled: 30, rx: 43 },
        isLoaded: true,
        description: "Squat into press.",
        cues: ["One fluid motion"],
    },
    {
        name: "Kettlebell Swing",
        abbreviation: "KBS",
        modality: "W",
        stimulusTags: ["power", "endurance"],
        equipmentRequired: ["kettlebells"],
        bodyweightOnly: false,
        family: "hinge",
        variants: ["Russian KBS"],
        progressions: [
            { level: "beginner", variant: "Russian KBS" },
            { level: "scaled", variant: "KBS" },
            { level: "rx", variant: "American KBS" },
        ],
        defaultLoadKg: { beginner: 8, scaled: 16, rx: 24 },
        isLoaded: true,
        description: "Ballistic hinge.",
        cues: ["Snap hips"],
    },
    {
        name: "Wall Ball",
        abbreviation: "WB",
        modality: "W",
        stimulusTags: ["endurance", "stamina"],
        equipmentRequired: ["box"], // Placeholder for ball
        bodyweightOnly: false,
        family: "squat",
        variants: [],
        progressions: [
            { level: "beginner", variant: "Air Squat" },
            { level: "scaled", variant: "Wall Ball (14lb)" },
            { level: "rx", variant: "Wall Ball (20lb)" },
        ],
        isLoaded: true,
        description: "Squat and throw.",
        cues: ["Target hit"],
    },
    {
        name: "SDHP",
        modality: "W",
        stimulusTags: ["power", "stamina"],
        equipmentRequired: ["barbell"],
        bodyweightOnly: false,
        family: "pull",
        variants: ["KB SDHP"],
        progressions: [
            { level: "beginner", variant: "KB SDHP" },
            { level: "scaled", variant: "Barbell SDHP" },
            { level: "rx", variant: "Barbell SDHP" },
        ],
        defaultLoadKg: { beginner: 15, scaled: 30, rx: 43 },
        isLoaded: true,
        description: "Sumo Deadlift High Pull.",
        cues: ["High elbows"],
    },
    {
        name: "Dumbbell Snatch",
        modality: "W",
        stimulusTags: ["power", "stamina"],
        equipmentRequired: ["dumbbells"],
        bodyweightOnly: false,
        family: "pull",
        variants: [],
        progressions: [
            { level: "beginner", variant: "DB Snatch (15lb)" },
            { level: "scaled", variant: "DB Snatch (35lb)" },
            { level: "rx", variant: "DB Snatch (50lb)" },
        ],
        isLoaded: true,
        description: "Single-arm power.",
        cues: ["Punch up"],
    },

    // --- Monostructural (M) ---
    {
        name: "Run",
        modality: "M",
        stimulusTags: ["endurance"],
        equipmentRequired: [],
        bodyweightOnly: true,
        family: "locomotion",
        variants: ["Shuttle Run"],
        progressions: [
            { level: "beginner", variant: "Walk/Jog" },
            { level: "scaled", variant: "Run" },
            { level: "rx", variant: "Run" },
        ],
        isLoaded: false,
        description: "Natural locomotion.",
        cues: ["Midfoot strike"],
    },
    {
        name: "Row (Erg)",
        modality: "M",
        stimulusTags: ["endurance", "stamina"],
        equipmentRequired: ["rower"],
        bodyweightOnly: false,
        family: "locomotion",
        variants: [],
        progressions: [
            { level: "beginner", variant: "Row (Erg)" },
            { level: "scaled", variant: "Row (Erg)" },
            { level: "rx", variant: "Row (Erg)" },
        ],
        isLoaded: false,
        description: "Conditioning pulling.",
        cues: ["Legs-hips-arms"],
    },
    {
        name: "Assault Bike",
        modality: "M",
        stimulusTags: ["endurance", "stamina"],
        equipmentRequired: ["assault_bike"],
        bodyweightOnly: false,
        family: "locomotion",
        variants: [],
        progressions: [
            { level: "beginner", variant: "Bike" },
            { level: "scaled", variant: "Assault Bike" },
            { level: "rx", variant: "Assault Bike" },
        ],
        isLoaded: false,
        description: "High-intensity bike.",
        cues: ["Push and pull"],
    },
    {
        name: "Double-Under",
        abbreviation: "DU",
        modality: "M",
        stimulusTags: ["coordination", "endurance"],
        equipmentRequired: ["jump_rope"],
        bodyweightOnly: false,
        family: "jump",
        variants: ["Single-Under"],
        progressions: [
            { level: "beginner", variant: "Single-Under" },
            { level: "scaled", variant: "DU Attempt" },
            { level: "rx", variant: "Double-Under" },
        ],
        isLoaded: false,
        description: "Jump rope skill.",
        cues: ["Wrists only"],
    },

];

async function seed() {
    await mongoose.connect(MONGODB_URI);
    console.log("Connected to MongoDB");

    // Clear existing test data
    await Movement.deleteMany({});
    console.log("Cleared existing movements");

    // Insert test movements
    const result = await Movement.insertMany(testMovements);
    console.log(`Seeded ${result.length} movements`);

    await mongoose.disconnect();
    console.log("Done!");
}

seed().catch(console.error);
